# Generated by Django 6.0.5 on 2026-05-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct'), ('scope2', 'Scope 2 - Electricity'), ('scope3', 'Scope 3 - Value Chain')], max_length=10)),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel Stay'), ('ground_transport', 'Ground Transport')], max_length=30)),
                ('raw_value', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('co2e_kg', models.FloatField(blank=True, null=True)),
                ('activity_date', models.DateField()),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flagged_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_rows', to='accounts.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.emissionrow')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('raw_row_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingestion.datasource')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emissionrow',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionrun'),
        ),
    ]
